mytsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog import views
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^home/$', views.home, name='home'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'', include('mama_cas.urls')),
    url(r'^cas/', include('mama_cas.urls')),
    url(r'^category/$', views.category, name='category'),
    url(r'^process_register/$', views.process_register, name='process_register'),
    url(r'^buy_bids/$', views.buy_bids, name='buy_bids'),
    url(r'^addproduct/$', views.addproduct, name='addproduct'),
    url(r'^orderhistory/$', views.orderhistory, name='orderhistory'),
    url(r'^searchproducts/$', views.searchproducts, name='searchproducts'),
    url(r'^viewproduct/(?P<category_id>\d+)/$', views.viewproduct, name='viewproduct'),    
    url(r'^products_in_category/(?P<category_id>\d+)/$', views.products_in_category, name='products_in_category'),
    url(r'^processbids/$', views.processbids, name='processbids'),
    url(r'^getmaxbidder/$', views.getmaxbidder.as_view(), name='getmaxbidder'),
    url(r'^loginform/$', views.loginform, name='loginform'),
    url(r'^mybidproducts/$', views.mybidproducts, name='mybidproducts'),
    url(r'^changePassword/$', views.changePassword, name='changePassword'),
    url(r'^account_management/$', views.account_management, name='account_management'),
    url(r'^logoutview/$', views.logoutview, name='logoutview'),
    url(r'^CurrrentDateTime/$', views.CurrrentDateTime.as_view(), name='CurrrentDateTime'),
    url(r'^buybidservice/$', views.buybidservice.as_view(), name='buybidservice'),
    url(r'^search/$', views.search.as_view(), name='search'),
    url(r'^sold/$', views.sold, name='sold'),
    url(r'^autobid/$', views.autobid.as_view(), name='autobid'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),

]

blog/models.py
from django.db import models
from django.conf import settings
from datetime import datetime, timedelta


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    card_no = models.CharField(max_length=16, null=True)
    exp_date = models.DateField(null=True)
    cvv = models.CharField(max_length=3, null=True)
    bids = models.PositiveSmallIntegerField(default=0)

class CATEGORY(models.Model):
    category_name = models.CharField(max_length=200)


class PRODUCT(models.Model):
    product_name = models.CharField(max_length=100)
    product_desc = models.CharField(max_length=200)
    price = models.IntegerField()
    product_path = models.CharField(max_length=200)
    category_id = models.ForeignKey(CATEGORY)
    owner = models.IntegerField()
    status = models.PositiveSmallIntegerField(default=1)  # 1 ==> product available, 0 ==> product sold
    expdatetime=models.DateTimeField(default=datetime.now()+timedelta(minutes=60))


class SOLD(models.Model):
    product_id = models.IntegerField()
    bid_value = models.IntegerField()
    old_owner = models.IntegerField()
    new_owner = models.IntegerField()

class BIDFORYOU(models.Model):
    product_id = models.IntegerField()
    bid_value = models.IntegerField()
    bidder_id = models.IntegerField()
    


class TRANSACT(models.Model):
    product = models.ForeignKey(PRODUCT)
    bidder_id = models.IntegerField()
    bid_value = models.IntegerField(default=1)

blog/forms.py
from django import forms
from blog.models import CATEGORY



class CustomerForm(forms.Form):
	firstname = forms.CharField(label='First Name', max_length=100, required=True)
	lastname = forms.CharField(label='last Name', max_length=100, required=True)
	emailid = forms.EmailField(label='Email Id', max_length=100, required=True)
	username = forms.CharField(label='Username', max_length=20, required=True)
	password = forms.CharField(widget=forms.PasswordInput(), label='Password', max_length=20, required=True)
	card_no = forms.CharField(label='Card No.', max_length=16, required=True)
	exp_date = forms.DateField(label='Expiry Date', required=True)
	cvv = forms.IntegerField(label='CVV', required=True)

class UpdateForm(forms.Form):
	firstname = forms.CharField(label='First Name', max_length=100, required=True)
	lastname = forms.CharField(label='last Name', max_length=100, required=True)
	emailid = forms.EmailField(label='Email Id', max_length=100, required=True)
	username = forms.CharField(label='Username', max_length=20, required=True)
	card_no = forms.CharField(label='Card No.', max_length=16, required=True)
	exp_date = forms.DateField(label='Expiry Date', required=True)
	cvv = forms.IntegerField(label='CVV', required=True)


class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20, required=True)
	password = forms.CharField(widget=forms.PasswordInput(), required=True)

class passwordForm(forms.Form):
        oldpassword = forms.CharField(label='Old Password',widget=forms.PasswordInput(), required=True)
	password = forms.CharField(label='New Password',widget=forms.PasswordInput(), required=True)
	password1 = forms.CharField(label='Confirm New Password',widget=forms.PasswordInput(), required=True)

class BidBuy(forms.Form):
	no_of_bids = forms.IntegerField(label='Number of Bids', required=True)

	


class ProductForm(forms.Form):
    fileName = forms.FileField(label='Image path',required=True)
    productname = forms.CharField(label='Product Name', max_length=100, required=True)
    product_desc = forms.CharField(label='Product Description', max_length=200, required=True)
    price = forms.IntegerField(label='Estimated Price', required=True)
    #product_path = forms.CharField(label='Image path', max_length=200, required=True)
    expdatetime = forms.CharField(label='Expiry Date Time', required=True,widget=forms.DateInput(attrs={'class':'some_class'}))
    expdatetimehidden=forms.CharField(widget=forms.HiddenInput())
    cat = CATEGORY.objects.all()
    CHOICES = []
    for c in cat:
        CHOICES.append((c.id, c.category_name))
    category = forms.ChoiceField(choices=tuple(CHOICES), required=True, label='Category')

					


	

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.db.models import Max
from blog.models import CATEGORY, PRODUCT, TRANSACT, SOLD, UserProfile, BIDFORYOU
from blog.forms import CustomerForm, BidBuy, ProductForm, LoginForm, UpdateForm, passwordForm
from django.contrib.auth import logout
from datetime import datetime, timedelta
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework import authentication, permissions
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.views.decorators.cache import never_cache
import json


def handle_uploaded_file(f, fileName, category_name):
    with open('blog/static/blog/images/' + category_name + '/' + fileName, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def searchproducts(query):
    products_obj = PRODUCT.objects.filter(product_name__icontains=query)
    products = []
    for p in products_obj:
        products.append(p)
        # info_dict = {'products': products, 'error': ''}
    return products



class autobid(APIView):
    renderer_classes = (JSONRenderer, )

    @never_cache
    def get(self, request, format="json"):
        userid=request.user.id
        bidvalue=request.GET['bid_val']
        productid=request.GET['product_id']
        flag=request.GET['flag']
        transact_obj, created = BIDFORYOU.objects.get_or_create(product_id=productid, bidder_id=userid)
        transact_obj.bid_value = bidvalue
        transact_obj.save()
        return Response({'auto_bid_val':transact_obj.bid_value})

    @never_cache
    def post(self, request, format="json"):
        userid=request.user.id
        bidvalue=request.POST['bid_val']
        productid=request.POST['product_id']
        flag=request.POST['flag']
        transact_obj, created = BIDFORYOU.objects.get_or_create(product_id=productid, bidder_id=userid)
        transact_obj.bid_value = bidvalue
        transact_obj.save()
        return Response({'auto_bid_val':transact_obj.bid_value})


def bidforyou():
    # products_obj = PRODUCT.objects.all()
    #transact_obj = TRANSACT.objects.all()

    bidforyou_obj = BIDFORYOU.objects.all()

    for b in bidforyou_obj:
        print b.product_id
        transact_obj,created = TRANSACT.objects.get_or_create(product_id=b.product_id, bidder_id=b.bidder_id)

        bidder_obj = TRANSACT.objects.filter(product_id=b.product_id).aggregate(Max('bid_value'))
        max_bid = bidder_obj['bid_value__max']
        if transact_obj.bid_value < max_bid:
            newbid = max_bid + 1
            #print newbid
            transact_obj.bid_value = newbid
            #print newbid
            if newbid <= b.bid_value:
                userprof = UserProfile.objects.get(user_id=b.bidder_id)
                userprof.bids = transact_obj.bid_value + userprof.bids
                userprof.bids = int(userprof.bids) - int(newbid)
                error = ''
                if userprof.bids >= 0:
                    userprof.save()
                    transact_obj.save()
                error = 'You do not have enough balance'



def index(request):
    return render(request, 'blog/index.html')


def category(request):
    if request.user.is_authenticated():
        cat = CATEGORY.objects.all()
        CHOICES = []
        for c in cat:
            CHOICES.append((c.id, c.category_name))
        context = {'choices': tuple(CHOICES)}
        return render(request, 'blog/category.html', context)
    else:
        return HttpResponseRedirect(reverse('loginform'))


def loginform(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    cat = CATEGORY.objects.all()
                    CHOICES = []
                    for c in cat:
                        CHOICES.append((c.id, c.category_name))
                    products_obj = PRODUCT.objects.filter(category_id_id=1, status=1).exclude(owner=request.user.id)
                    products = []
                    for p in products_obj:
                        products.append(p)
                    info_dict = {'products': products, 'error': '', 'choices': tuple(CHOICES)}
                    return render(request, 'blog/products_in_category.html', info_dict)
                # return HttpResponseRedirect(reverse('products_in_category',kwargs={'category_id':1})
                else:
                    msg = "Dear ", user.get_full_name(), ", your account is not active!"
                    form = LoginForm()
                    return render(request, 'blog/login.html', {'error': 'Invalid Credentials', 'form': form})
            else:
                msg = "hello"
                form = LoginForm()
                return render(request, 'blog/login.html', {'error': 'Invalid Credentials', 'form': form})
        else:
            form = LoginForm()
            return render(request, 'blog/login.html', {'error': 'Invalid Credentials', 'form': form})

    elif request.user and request.user.id is not None:
        # msg = 'hell'
        #profile = UserProfile.objects.filter(user_id=request.user.id)
        if UserProfile.objects.filter(user_id=request.user.id).exists():
            msg = 'helolo'

        else:
            profile1 = UserProfile.objects.create(user_id=request.user.id);
            profile1.save()
        #profile = UserProfile.objects.create(user_id=request.user.id, card_no='76868768', exp_date=0000-00-00, cvv='111')
        #profile.save();
        return HttpResponseRedirect(reverse('account_management'))
    else:
        form = LoginForm()
        context = RequestContext(request, {'request': request, 'user': request.user, 'form': form})
        return render_to_response('blog/login.html', context_instance=context)
        # return render(request, 'blog/login.html', {'form': form})


def changePassword(request):
    if request.method == 'POST':
        form = passwordForm(request.POST)
        if form.is_valid():
            old = form.cleaned_data['oldpassword']
            new = form.cleaned_data['password']
            new1 = form.cleaned_data['password1']
            if request.user.is_authenticated():
                if request.user.is_active:
                    user = User.objects.get(pk=request.user.id)
                    user1 = authenticate(username=user.username, password=old)
                    if user1 is not None:
                        if user.is_active:
                            if new == new1:
                                user.set_password(new)
                                user.save()
                                return HttpResponseRedirect(reverse('account_management'))
                            else:
                                form = passwordForm()
                                return render(request, 'blog/changePassword.html', {'form': form})
                        else:
                            form = passwordForm()
                            return render(request, 'blog/changePassword.html', {'form': form})
                    else:
                        form = passwordForm()
                        return render(request, 'blog/changePassword.html', {'form': form})
                else:
                    return HttpResponseRedirect(reverse('loginform'))
        else:
            form = passwordForm()
            return render(request, 'blog/changePassword.html', {'form': form})
    else:

        form = passwordForm()
        return render(request, 'blog/changePassword.html', {'form': form})


def account_management(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            form = UpdateForm(request.POST)
            if form.is_valid():

                firstname = form.cleaned_data['firstname']
                lastname = form.cleaned_data['lastname']
                emailid = form.cleaned_data['emailid']
                username = form.cleaned_data['username']
                # password = form.cleaned_data['password']
                card_no = form.cleaned_data['card_no']
                exp_date = form.cleaned_data['exp_date']
                cvv = form.cleaned_data['cvv']
                user = User.objects.get(pk=request.user.id)
                profile = UserProfile.objects.get(user_id=request.user.id)
                user.first_name = firstname
                user.last_name = lastname
                user.email = emailid
                user.username = username
                #user.set_password(password)
                user.save()
                profile.card_no = card_no
                profile.exp_date = exp_date
                profile.cvv = cvv
                profile.save()

                return HttpResponseRedirect(reverse('account_management'))
            else:
                return HttpResponseRedirect(reverse('account_management'))
        else:


            user = User.objects.get(pk=request.user.id)
            profile = UserProfile.objects.get(user_id=request.user.id)

            form = UpdateForm(initial={'firstname': user.first_name, 'lastname': user.last_name, 'emailid': user.email,
                                       'username': user.username, 'card_no': profile.card_no,

blog/templates/blog/account.html
{% extends 'blog/base.html' %}
{% block content %}
{% load staticfiles %}

<table border="0" align="centre">
	<tr>
		<td align="center" valign="middle"><img style="margin-left:50px;" src={% static 'blog/images/4/account.png' %} alt="" /></td>
		<td style="border:1pt solid orange;border-style: solid;border-width: 5px; margin-left:10px;" align="center" valign="middle" >
			<h1 class="mainmenu pull-left" style="margin-left:70px;margin-right:150px;color:orange;">Welcome to E-BID's Account Page</h1>
			<br>
			<br>
			<br>
			<br>
			<div class="signup-form" style="margin-left:0px">
			<form action="{% url 'account_management' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<table>
			{{ form.as_table }}
			<tr><td></td><td><a href={% url 'changePassword' %} >Change Password</a></td>
			<tr><td></td><td><input type="submit" value="Submit"/></td>
			</tr>
			</table>
			</div>
		</td>
		<td align="center" valign="middle">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
	</tr>	
</table>
<br>
<br>
<br>
{% endblock content %}

blog/templates/blog/addproduct.html
{% extends 'blog/base.html' %}
{% block content %}
{% load staticfiles %}

<table border="0" align="centre">
	<tr>
		<td><img style="margin-left:100px" src={% static 'blog/images/4/shopping.png' %} alt="" /></td>
		<td align="center" valign="middle" >
			<h1 style="color:orange">Welcome to E-BID's Add Product Page</h1>
		<div class="signup-form" style="margin-left:0px">
			<span id="error_mag" style ="color: red;">{{ error }}</span>
			<form class="signup-form" style="color:orange" action="{% url 'addproduct' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<table>
			{{ form.as_table }}
			<tr><td></td><td><br><input type="submit" value="Submit"/></td></tr>
			</table>
			</form>	
			<div>
		</td>
		
	</tr>	
</table>
<script>
$('.some_class').datetimepicker({
dateFormat: 'dd-mm-yy'
});
$(document).ready(function(){
    $("#id_expdatetime").change(function(){
        var expdatetime=$("#id_expdatetime").val();
       expdatetime=expdatetime.replace(/\//g, "-");
        $("#id_expdatetimehidden").val(expdatetime+":00");
        //alert($("#id_expdatetimehidden").val());
    });
});
</script>
{% endblock content %}

blog/templates/blog/buybid.html
{% extends 'blog/base.html' %}
{% block content %}
{% load staticfiles %}
<style type="text/css">
    .inputclass {
  background: #F0F0E9;
  border: medium none;
  color: #696763;
  display: block;
  font-family: 'Roboto', sans-serif;
  font-size: 14px;
  font-weight: 300;
  height: 40px;
  margin-bottom: 10px;
  outline: medium none;
  padding-left: 10px;
  width: 100%;
}

.login-form form span{
  line-height: 25px;
}

.inputclass input {
  width: 15px;
  float: left;
  height: 15px;
  margin-right: 5px;
}



.btn {
  background: #FE980F;
  border: medium none;
  border-radius: 0;
  color: #FFFFFF;
  display: block;
  font-family: 'Roboto', sans-serif;
  padding: 6px 25px;
}
</style>
<table border="0" align="centre">
	<tr>
		<td align="center" valign="middle"><img style="margin-left:125px" src={% static 'blog/images/4/doll2.png' %} alt="" /></td>
		<td align="center" valign="middle" >
			<h1 style="margin-left:110px; color:orange">Buy bids</h1>
			<span style="width:200px;margin-left:110px;color: red;" id="error_msg">{{ error }}</span>
			<pre style="width:400px;margin-left:120px;color:orange" ><h3> $1=1 bid</h3>
            <h4>Available Bids: $<span id="available_bids"></span></h4></pre>
			<div>
			<div  class="login-form">

			<table>
			<tr><td></td><td><input  style="width:200px;margin-left:120px;" class="inputclass" id="buybid_text" type="text" /></td></tr>
			<tr><td></td><td style="text-align:center"><input style="width:200px;margin-left:120px;" class="btn" id="buybid_button" type="button" value="Submit"/></td></tr>
			</table>

			</div>
			</div>
			
		</td>
		<td><img style="margin-left:100px" src={% static 'blog/images/4/doll2.png' %} alt="" /></td>
	</tr>	
</table>
<br><br><br>
<script>
var buybidserviceURL = {% url 'buybidservice' %};

    $(document).ready(function(){
    bid_ajax();
        $("#buybid_button").click(function(){
            bid_ajax();
        });
    });

    function bid_ajax(){
    var bid_val=$("#buybid_text").val();

             if(bid_val<=0 || bid_val=="" || isNaN(bid_val))
             {
                bid_val=0;
             }
             $.ajax({
				        url : buybidserviceURL, // the endpoint
				        type : "GET", // http method
				        beforeSend: function(xhr, settings) {
					        if (!this.crossDomain) {
					            xhr.setRequestHeader("X-CSRFToken", csrftoken);
					        }
					    },
						data:{
							'no_of_bids':bid_val
						},
				        success : function(data) {

							$("#available_bids").html(data['available_bids']);
				        },

				        // handle a non-successful response
				        error : function(xhr,errmsg,err) {
				           console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
				        }
		    });

    }
</script>

{% endblock content %}

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>Welcome {{ user.first_name }}  {{ user.last_name }} to E-BID's Category Page</h1>
<table>
{% for c in choices %}
    <tr>
    	<td id={{ c.0 }} > <a href={% url 'products_in_category' c.0 %} > {{ c.1 }} </a></td>
    </tr>
{% endfor %}
</table>
{% endblock content %}

blog/templates/blog/changePassword.html
{% extends 'blog/base.html' %}
{% block content %}
<h1 class="mainmenu pull-left" style="margin-left:400px;color: #808080;">Change Your Password Here</h1>

<br>
<br>
<br>
<br>
<div class="login-form" style="margin-left:500px">


<form action="{% url 'changePassword' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
<table>
{{ form.as_table }}
<tr><td></td><td><input type="submit" value="Change Your Password"/></td>

</tr>



</table>


</div>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base1.html' %}

{% block main %}
 <div>
 <h1>Third-party authentication demo</h1>

 <p>
   <ul>
   {% if user and not user.is_anonymous %}
     <li>
       <a>Hello {{ request.user.id }}!</a>
     </li>
     <li>
       <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
                                <li><a href="{% url 'account_management' %}" ><i class="fa fa-user"></i> Account</a></li>
								                                 <li class="dropdown"><a href="{% url 'products_in_category' 1 %}">Category<i class="fa fa-angle-down"></i></a>

     </li>
   {% else %}
     <li>
       <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
     </li>
     <li>
       <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a>
     </li>
     <li>
       <a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">Login with Twitter</a>
     </li>
   {% endif %}
   </ul>
 </p>
 </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block content %}
{% load staticfiles %}
 	
    <script src={% static 'blog/js/js-image-slider.js' %} ></script>
    
    
    <div id="sliderFrame">
        <div id="slider">
        	<img src={% static 'blog/images/4/slider-1.jpg' %} alt="" />
        	<img src={% static 'blog/images/4/slider-2.jpg' %} alt="" />
        	<img src={% static 'blog/images/4/slider-3.jpg' %} alt="" />
        	<img src={% static 'blog/images/4/slider-4.jpg' %} alt="" />
        </div>
        <!--Custom navigation buttons on both sides-->
        <div class="group1-Wrapper">
            <a onclick="imageSlider.previous()" class="group1-Prev"></a>
            <a onclick="imageSlider.next()" class="group1-Next"></a>
        </div>
        <!--nav bar-->
        <div style="text-align:center;padding:20px;z-index:20;">
            <a onclick="imageSlider.previous()" class="group2-Prev"></a>
            <a id='auto' onclick="switchAutoAdvance()"></a>
            <a onclick="imageSlider.next()" class="group2-Next"></a>
        </div>
    </div>
    <script type="text/javascript">
        //The following script is for the group 2 navigation buttons.
        function switchAutoAdvance() {
            imageSlider.switchAuto();
            switchPlayPauseClass();
        }
        function switchPlayPauseClass() {
            var auto = document.getElementById('auto');
            var isAutoPlay = imageSlider.getAuto();
            auto.className = isAutoPlay ? "group2-Pause" : "group2-Play";
            auto.title = isAutoPlay ? "Pause" : "Play";
        }
        switchPlayPauseClass();
    </script>
{% endblock content %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block content %}
{% load staticfiles %}
<div class ="row" style ="margin-left:160px;">
<table border="0" align="centre">
	<tr>
		<td align="center" valign="middle"><img style="margin-left:0px;" src={% static 'blog/images/4/log.png' %} alt="" /></td>
		<td style="border:1pt solid orange;border-style: solid;border-width: 2px;" align="center" valign="middle" >
			<h1 class="mainmenu pull-left" style="margin-right: 150px;margin-left: 150px;;color:orange;">&nbsp;Login in to e-Bid.com</h1>
			<br><br><br><br><br>
			<div class="login-form" style="margin-left:20px;">
			<form action="{% url 'loginform' %}" method="post" enctype="multipart/form-data">
						{% csrf_token %}
			{% if error %}
      {{ error }}!

   {% endif %}
			{% csrf_token %}
			<table>
			{{ form.as_table }}
			<tr><td></td><td><input type="submit" value="Submit"/></td>
			</tr>
			<tr><td><a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook<img href={% static 'blog/images/facebook.jpeg' %} ></img></a></td><td><a href= "{% url 'process_register' %}" style="margin-left:90px;font-size: 150%;color:orange"><img style="margin-left:10px;" src={% static 'blog/images/4/register1.png' %} alt="Register Here" /></a></a>
</td></tr>
			</table>
						

			</div>
		</td>
		<td><img style="margin-left:2px;" src={% static 'blog/images/4/log.png' %} alt="" /></td>
	</tr>	
</table>
</div>
<br><br><br><br>
{% endblock content %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% block content %}
{% load staticfiles %}

<table border="0" align="centre">
	<tr>
		<td align="center" valign="middle"><img style="margin-left:50px;" src={% static 'blog/images/4/register.png' %} alt="" /></td>
		<td style="border:1pt solid orange;border-style: solid;border-width: 5px; margin-left:10px;" align="center" valign="middle" >
			<h1 class="mainmenu pull-left" style="margin-left:70px;margin-right:150px;color:orange;">Welcome to E-BID's Registration Page</h1>
			<br>
			<br>
			<br>
			<br>
			<div class="signup-form" style="margin-left:0px">
			<form action="{% url 'process_register' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<table>
			{{ form.as_table }}
			<tr><td></td><td><input type="submit" value="Submit"/></td>
			</tr>
			</table>
			<a href= "{% url 'loginform' %}" style="margin-left:100px;font-size: 150%;color:orange;"><img style="margin-left:10px;" src={% static 'blog/images/4/register1.png' %} alt="" /></a>
			</div>
		</td>
		<td align="center" valign="middle">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
	</tr>	
</table>
<br>
<br>
<br>
{% endblock content %}